export async function api(path,body){
 const response=await fetch('/api/'+path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(230000)});
 let data;try{data=await response.json();}catch{throw Error('本机服务响应异常，请确认 V0.2 服务正在运行。');}if(!response.ok)throw Error(data.error||'请求失败');return data;
}
export function invalidateMemory(state,id){
 state.revision=(state.revision||0)+1;state.reply=null;state.review=null;
 for(const t of state.thoughts){if(t.id===id){delete t.ai;delete t.workflow;delete t.runId;t.links=[];}else if(t.links?.some(l=>l.recordId===id)){t.links=t.links.filter(l=>l.recordId!==id);t.relationState='stale';}}
 state.feedback=(state.feedback||[]).filter(f=>f.from!==id&&f.to!==id);
}
export function createMemoryUI({getState:S,save,render,navigate,toast,showDialog,closeDialog,detail,esc:e,time,catalog}){
 let config={configured:false,baseUrl:'',model:'',hasKey:false,jsonMode:true};let busy=false,queue=Promise.resolve(),modelMessage='',modelTesting=false;let questionDraft='',fromDraft='',toDraft='';
 const label={queued:'等待分析',running:'正在理解记录',relating:'正在寻找相关记忆',done:'理解与关联已完成',failed:'分析未完成',unconfigured:'等待配置模型',stale:'记录已更新，待重新关联'};
 const button=(name,text,data='',cls='button outlined small')=>`<button type="button" class="${cls}" data-action="${name}" ${data}>${text}</button>`;
 const date=s=>new Date(s).toLocaleDateString('zh-CN',{timeZone:'Asia/Shanghai',year:'numeric',month:'numeric',day:'numeric'});
 function usable(){return S().thoughts.filter(t=>!t.demo&&t.text?.trim());}
 function packed(){return usable().map(t=>({id:t.id,text:t.text,createdAt:t.createdAt,audioId:t.audioId,position:t.position,context:t.context,correction:t.correction||''}));}
 function redraw(){if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;if(['journey','recall','review','settings','thoughts'].includes(location.hash.slice(1)))render();const id=document.querySelector('dialog[open][data-kind="detail"]')?.dataset.thoughtId;if(id&&S().thoughts.some(t=>t.id===id))detail(id);}
 async function refresh(){try{config=await api('model/config');}catch{config={...config,configured:false};}redraw();return config;}
 function changed(id){invalidateMemory(S(),id);}
 function schedule(id){
  const t=S().thoughts.find(t=>t.id===id);if(!t?.text?.trim())return;
  const runId=crypto.randomUUID();t.runId=runId;t.workflow={status:'queued'};save();
  queue=queue.catch(()=>{}).then(async()=>{
   const live=()=>S().thoughts.find(x=>x.id===id&&x.runId===runId);if(!live())return;
   try{
    config=await api('model/config');if(!config.configured){t.workflow={status:'unconfigured'};save();redraw();return;}
    t.workflow={status:'running'};save();redraw();
    const result=await api('workflow/understand',{records:packed(),currentId:id});if(!live())return;
    t.ai=result;t.context=result.context||t.context;t.workflow={status:'relating'};save();redraw();
    // If the memory set changes while comparing, do not keep stale relations.
    const revision=S().revision;
    if(usable().length>1){const linked=await api('workflow/relate',{records:packed(),currentId:id,feedback:S().feedback||[]});if(!live())return;if(revision!==S().revision){t.workflow={status:'failed',error:'分析期间记录有变化。当前理解已保留，请重新分析以更新关联。'};save();redraw();return;}t.links=linked.links;t.relationMeta=linked.meta;}
    else t.links=[];
    t.workflow={status:'done'};save();redraw();toast('想法已理解，原话和分析依据都已保留。');
   }catch(error){if(live()){t.workflow={status:'failed',error:error.message};save();redraw();toast('分析暂未完成，原话已保存，可重试。');}}
  });return queue;
 }
 function evidence(list){return `<div class="evidence">${(list||[]).map(c=>{const t=S().thoughts.find(t=>t.id===c.recordId);return t?`<button data-action="detail" data-id="${e(t.id)}"><q>${e(c.quote)}</q><small>${date(t.createdAt)} · ${time(t.position)} · 查看原话</small></button>`:'';}).join('')}</div>`;}
 function resultHtml(result){if(!result)return '';return `${(result.items||[]).map(i=>`<article class="memory-finding"><span class="tag">${e(i.kind)}</span><p>${e(i.text)}</p>${evidence(i.evidence)}</article>`).join('')}${result.gaps?.length?`<div class="memory-gaps"><strong>还不确定的地方</strong>${result.gaps.map(g=>`<p>${e(g)}</p>`).join('')}</div>`:''}${meta(result.meta)}`;}
 function meta(m){return m?`<details class="execution-details"><summary>查看本次分析依据</summary><p>${e(m.model||'未调用模型')} · 提示词 ${e(m.promptVersion)} · ${m.count||0} / ${m.total||0} 条记录 · ${e(m.retrieval||'当前记录')}${m.createdAt?' · '+date(m.createdAt):''}</p><p>引用已与原话核对；语义是否准确仍由你判断。</p></details>`:'';}
 function banner(){return `<div class="experience-banner"><div><span class="tag">V0.2 全真模拟版</span><strong>我的求职与实习探索</strong><p>5 期真实播客，把听到的建议和自己的经历联系起来。</p></div><button class="button dark" data-nav="journey">开始体验路线 →</button></div>`;}
 function journey(){const s=S(),n=usable().length,linked=s.thoughts.reduce((a,t)=>a+(t.links?.length||0),0);return `<section class="page-heading"><div><div class="eyebrow">REAL VOICES. YOUR OWN THOUGHTS.</div><h1>把求职路上的想法，<br>一点点连起来。</h1><p>从五期真实播客开始。听、留下反应，再回来看自己。</p></div><span class="tag">V0.2 全真模拟版</span></section><div class="workflow-strip">${[['01','记录理解',`${n} 条真实表达`],['02','历史关联',`${linked} 个待你判断的联系`],['03','问题回忆',s.reply?'已留下回答':'带着一个问题来问'],['04','阶段回顾',s.review?'已生成回顾':'看见反复出现的问题']].map(([i,t,d])=>`<div><small>${i}</small><strong>${t}</strong><p>${d}</p></div>`).join('')}</div><section class="experience-setup"><div><strong>${config.configured?(config.verifiedAt?'模型已连接 · ':'配置已保存 · ')+e(config.model):'先接好你的大模型'}</strong><p>${config.configured?'每次记录会真实分析，可在设置中暂停。':'在设置里填写 API 地址、模型名称和密钥，测试连接后开始。没有配置时仍可听和记录。'}</p></div><button class="button outlined" data-nav="settings">${config.configured?'模型设置':'配置并测试 API'}</button></section><div class="journey-list">${catalog.map((a,i)=>{const ts=s.thoughts.filter(t=>t.audioId===a.id);return `<article class="journey-card"><span class="journey-index">0${i+1}</span><div><div class="eyebrow orange-text">${e(a.subtitle)}</div><h2>${e(a.title)}</h2><p>${e(a.author)} · ${Math.round(a.duration/60)} 分钟 · ${date(a.publishedAt)} 发布</p><p class="journey-invite">${['留意你认同或不认同的求职建议。它让你想起了什么？','听到经历表达的方法时，想想自己有没有类似困惑。','哪些建议适合你的情况？哪些条件与你不同？','你做过的项目带来了什么真实经验？还有哪些疑问？','想到一次沟通经历，或者你还没尝试过的做法。'][i]}</p><div class="journey-actions">${button('journey-listen','从推荐片段开始',`data-id="${a.id}" data-at="${a.recommendedStart}"`,'button primary small')}${button('journey-listen','从头收听',`data-id="${a.id}" data-at="0"`)}<a href="${e(a.sourceUrl)}" target="_blank" rel="noopener noreferrer">节目原页 ↗</a><span>${ts.length?ts.length+' 条我的记录':'还没有记录'}</span></div></div></article>`;}).join('')}</div><section class="journey-next"><div><h2>留下几条记录以后</h2><p>无需听完五期。可以先跨两期各留一条，检查理解与关联，再提一个你真正关心的问题。最后生成回顾，判断它有没有帮助你想起被忘记的想法。</p></div><div><button class="button dark" data-nav="recall">问问过去的我</button><button class="button outlined" data-nav="review">生成阶段回顾</button></div></section><p class="source-note">节目来自「以鹅传鹅FM」「鹅厂wò谈会」，版权归原作者。这里提供本机个人体验。招聘信息以节目发布日期为背景，当前要求请查招聘官网。推荐片段仅是收听入口，不预设你的观点。</p>`;}
 function settings(){return `<section class="model-settings"><div class="section-title"><h2>连接你的大模型</h2><span class="tag">${config.configured?'已启用':'待配置'}</span></div><p>支持 Chat Completions 兼容接口。密钥只保存到本机服务，不写入浏览器记录，也不会显示在导出文件中。</p><div class="model-actions">${button('preset-aliyun','使用阿里云百炼')}${button('preset-deepseek','使用 DeepSeek')}</div><form id="model-form"><label class="field-label" for="model-base">API Base URL</label><input id="model-base" type="url" required value="${e(config.baseUrl)}" placeholder="填写服务商提供的 Base URL"><label class="field-label" for="model-name">模型名称</label><input id="model-name" required value="${e(config.model)}" placeholder="例如 qwen-plus；不要填写服务商名称"><label class="field-label" for="model-key">API Key ${config.hasKey?'（已保存；留空沿用）':''}</label><input id="model-key" type="password" autocomplete="off" ${config.hasKey?'':'required'} placeholder="在这里输入，不要发到聊天中"><label class="check-label"><input id="model-json" type="checkbox" ${config.jsonMode?'checked':''}> 使用 JSON 输出模式（服务商不支持时可关闭）</label><label class="check-label"><input id="model-enabled" type="checkbox" ${config.configured?'checked':''}> 启用 AI 分析：将我的文字、相关历史与播客片段转写发至此服务，按服务商规则计费</label><div class="model-actions"><button class="button primary" type="submit">保存配置</button>${button('test-model',modelTesting?'正在测试…':'测试连接',modelTesting?'disabled':'')}${button('retry-pending','分析尚未处理的记录')}</div><p id="model-message" role="status">${e(modelMessage||(config.verifiedAt?'连接已验证 · '+config.model:'保存配置后可测试连接。'))}</p></form></section>`;}
 function podcastNotes(a){return `<div class="podcast-source"><p>真实音频 · ${date(a.publishedAt)} 发布 <a href="${e(a.sourceUrl)}" target="_blank" rel="noopener noreferrer">查看节目原页 ↗</a></p><p>以下是节目提供的收听位置，属于章节导航。你留下想法后，会在本机转写当时前 90 秒的音频作为分析上下文。</p></div><div class="transcript">${a.listeningPoints.map(c=>`<button class="transcript-row" data-action="seek" data-at="${c.start}"><time>${time(c.start)}</time><p>${e(c.text)}</p></button>`).join('')}</div>`;}
 function thoughtPanel(t){const links=t.links||[];return `<section class="ai-thought"><div class="detail-label">理解这一刻 <span class="tag">${e(label[t.workflow?.status]||'待分析')}</span></div>${t.workflow?.error?`<p class="flow-error">${e(t.workflow.error)}</p>`:''}${t.ai?resultHtml(t.ai):'<p>原话已保存。启用模型后，这里会展示带依据的理解。</p>'}<div class="detail-actions">${button('analyze-thought',t.ai?'重新分析':'开始分析',`data-id="${t.id}"`)}${t.ai?button('understanding-good','理解准确',`data-id="${t.id}"`)+button('correct-understanding','补充或纠正',`data-id="${t.id}"`):''}</div>${t.correction?`<p class="correction-note">我的补充：${e(t.correction)}</p>`:''}${t.understandingFeedback==='good'?'<small>已记下：这次理解准确。</small>':''}<div class="detail-label relation-heading">与过去的联系</div>${links.map(l=>{const verdict=(S().feedback||[]).find(f=>f.from===t.id&&f.to===l.recordId)?.verdict;return `<article class="memory-link"><span class="tag">${e(l.relation)}</span><p>${e(l.reason)}</p>${evidence(l.evidence)}<div>${button('relation-yes',verdict==='confirmed'?'已确认有关':'确实有关',`data-id="${t.id}" data-other="${l.recordId}"`)}${button('relation-no','这两条无关',`data-id="${t.id}" data-other="${l.recordId}"`)}</div></article>`;}).join('')||`<p>${t.workflow?.status==='done'?'暂未找到有充分依据的关联。记录会随着你的使用继续积累。':'记录理解完成后，会尝试寻找相关历史。'}</p>`}</section>`;}
 function recall(){return `<section class="page-heading"><div><div class="eyebrow">ASK YOUR PAST SELF</div><h1>你以前，也想过这件事吗？</h1><p>从自己的记录里找回经历和依据。没有记录的地方，会如实告诉你。</p></div></section><form id="recall-form" class="memory-query"><label for="memory-question" class="field-label">现在困扰你的问题</label><textarea id="memory-question" required maxlength="2000" placeholder="例如：我总担心没有对口实习，之前听到的建议里，哪些和我的经历有关？">${e(questionDraft)}</textarea><button class="button primary" ${busy?'disabled':''}>${busy?'正在翻阅你的记录…':'找回相关记忆'}</button></form>${S().reply?`<section class="memory-result"><h2>${e(S().reply.question)}</h2>${resultHtml(S().reply)}${feedbackButtons('reply',S().reply)}</section>`:'<p class="quiet-empty">回答会引用你真实留下的话。先听一段、留一个想法，就能开始。</p>'}`;}
 function review(){return `<section class="page-heading"><div><div class="eyebrow">LOOK BACK, WITH EVIDENCE</div><h1>这些声音，让你想到了什么？</h1><p>跨音频回看反复出现的问题、可能的变化和仍待验证的想法。</p></div></section><form id="review-form" class="memory-query review-controls"><label>开始日期<input type="date" id="review-from" value="${e(fromDraft)}"></label><label>结束日期<input type="date" id="review-to" value="${e(toDraft)}"></label><button class="button primary" ${busy?'disabled':''}>${busy?'正在整理你的记录…':'生成阶段回顾'}</button></form><p class="subtle">不选日期则使用全部记录。日期按北京时间；每次生成会调用模型。</p>${S().review?`<section class="memory-result"><h2>这段时间的思考</h2><p>${e(S().review.range||'全部记录')}</p>${resultHtml(S().review)}${feedbackButtons('review',S().review)}</section>`:'<p class="quiet-empty">这里从空白开始。我们不会提前替你写好成长故事。</p>'}`;}
 function feedbackButtons(kind,result){return `<div class="result-feedback"><span>${result.feedback?result.feedback==='useful'?'已记录：有帮助':'已记录：还不够准确':'这次结果有帮助吗？'}</span>${button('result-useful','帮我想起了有用的事',`data-result="${kind}"`)}${button('result-inaccurate','还不够准确',`data-result="${kind}"`)}</div>`;}
 async function action(name,el){const id=el?.dataset.id;
  if(name==='preset-aliyun'||name==='preset-deepseek'){const base=document.querySelector('#model-base'),model=document.querySelector('#model-name');if(name==='preset-aliyun'){let u;try{u=new URL(base.value);}catch{}base.value=u?.hostname.endsWith('.aliyuncs.com')?u.origin+'/compatible-mode/v1':'https://dashscope.aliyuncs.com/compatible-mode/v1';model.value='qwen-plus';}else{base.value='https://api.deepseek.com';model.value='deepseek-flash';}toast('已填入接口示例。确认模型与密钥属于该服务后保存。');return true;}
  if(name==='test-model'){
   if(modelTesting)return true;modelTesting=true;el.disabled=true;el.textContent='正在测试…';modelMessage='正在保存并测试当前填写的配置…';
   const display=()=>{const node=document.querySelector('#model-message');if(node)node.textContent=modelMessage;};display();
   try{config=await api('model/config',modelFormData());const key=document.querySelector('#model-key');if(key)key.value='';await api('model/test',{});config=await api('model/config');modelMessage='连接成功 · '+config.model+' 已返回有效 JSON，可以开始伴听。';}
   catch(error){modelMessage='连接未成功：'+error.message;}finally{modelTesting=false;display();if(el.isConnected){el.disabled=false;el.textContent='测试连接';}toast(modelMessage);}return true;
  }
  if(name==='retry-pending'){for(const t of usable())if(t.workflow?.status!=='done')schedule(t.id);toast('尚未完成的记录已加入分析队列。');return true;}
  if(name==='analyze-thought'){schedule(id);await detail(id);return true;}
  if(name==='understanding-good'){const t=S().thoughts.find(t=>t.id===id);t.understandingFeedback='good';save();detail(id);return true;}
  if(name==='correct-understanding'){const t=S().thoughts.find(t=>t.id===id);showDialog(`<h2>我实际想表达的是</h2><p>补充说明会和原话一起供模型重新理解。</p><form id="correction-form" data-id="${id}"><textarea id="correction-text" required maxlength="2000" aria-label="纠正说明">${e(t.correction||'')}</textarea><button class="button primary">保存并重新分析</button></form>`,'纠正理解');return true;}
  if(name==='relation-yes'||name==='relation-no'){const s=S();s.feedback=(s.feedback||[]).filter(f=>!(f.from===id&&f.to===el.dataset.other));s.feedback.push({from:id,to:el.dataset.other,verdict:name==='relation-yes'?'confirmed':'rejected',createdAt:new Date().toISOString()});if(name==='relation-no')s.thoughts.find(t=>t.id===id).links=s.thoughts.find(t=>t.id===id).links.filter(l=>l.recordId!==el.dataset.other);s.reply=null;s.review=null;s.revision=(s.revision||0)+1;save();detail(id);return true;}
  if(name==='result-useful'||name==='result-inaccurate'){const result=S()[el.dataset.result];if(result)result.feedback=name==='result-useful'?'useful':'inaccurate';save();render();return true;}
  return false;
 }
 function modelFormData(){const f=document.querySelector('#model-form');return {baseUrl:f.querySelector('#model-base').value.trim(),model:f.querySelector('#model-name').value.trim(),apiKey:f.querySelector('#model-key').value.trim(),enabled:f.querySelector('#model-enabled').checked,jsonMode:f.querySelector('#model-json').checked};}
 async function submit(form){
  if(form.id==='model-form'){const message=document.querySelector('#model-message'),submit=form.querySelector('[type="submit"]');submit.disabled=true;try{config=await api('model/config',modelFormData());modelMessage='配置已保存，尚未验证连接。';form.querySelector('#model-key').value='';render();toast('配置已保存。点击「测试连接」验证服务。');}catch(error){message.textContent=error.message;}finally{if(submit.isConnected)submit.disabled=false;}return true;}
  if(form.id==='correction-form'){const t=S().thoughts.find(t=>t.id===form.dataset.id);if(!t)return true;const correction=form.querySelector('textarea').value.trim();changed(t.id);t.correction=correction;save();closeDialog();schedule(t.id);detail(t.id);return true;}
  if(!['recall-form','review-form'].includes(form.id))return false;
  if(busy)return true;let records=packed(),kind=form.id==='recall-form'?'recall':'review';
  if(kind==='recall')questionDraft=form.querySelector('textarea').value.trim();else{fromDraft=form.querySelector('#review-from').value;toDraft=form.querySelector('#review-to').value;if(fromDraft&&toDraft&&fromDraft>toDraft){toast('结束日期不能早于开始日期。');return true;}records=records.filter(r=>{const d=new Date(r.createdAt).toLocaleDateString('en-CA',{timeZone:'Asia/Shanghai'});return (!fromDraft||d>=fromDraft)&&(!toDraft||d<=toDraft);});}
  if(!records.length){toast('这个范围内还没有文字记录，先留下自己的想法吧。');return true;}
  const revision=S().revision;busy=true;render();
  try{const result=await api('workflow/'+kind,{records,question:questionDraft,feedback:S().feedback||[]});if(revision!==S().revision){toast('记录在分析期间发生变化，请重新生成。');return true;}const key=kind==='recall'?'reply':'review';S()[key]={...result,question:questionDraft,range:`${fromDraft||'最早记录'} — ${toDraft||'最新记录'}`};save();}catch(error){toast(error.message);}finally{busy=false;render();}return true;
 }
 for(const t of S().thoughts){if(['running','relating','queued'].includes(t.workflow?.status))t.workflow={status:'failed',error:'页面刷新中断了分析，请重试。'};}
 return {refresh,changed,schedule,banner,journey,settings,podcastNotes,thoughtPanel,recall,review,action,submit};
}
